services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: pizza_db
    ports:
      - "3306:3306"
    volumes:
      - /home/juaneins_uio/dockerdata/mysql_data:/var/lib/mysql
    networks:
      - pizza_network
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - pizza_network

networks:
  pizza_network:
    driver: bridge